/* global React, SEED */
// =============================================================================
// Dashboard — reusable sub-components & small modules
// =============================================================================

const { useState, useRef, useEffect, useMemo } = React;

// --- Icon helper ---
function Icon({ name, size = 16, style }) {
  return React.createElement('img', {
    src: `ds/assets/icons/${name}.svg`,
    width: size, height: size, alt: '',
    style: { display: 'inline-block', ...style },
  });
}

// --- Known people registry for click-to-lens text rendering -------------------
// Configured per-user via window.SEED.knownPeople (set by data-override.jsx,
// generated by the dashboard skill from your config). Each entry:
//   { match: '<text to detect>', name: '<full name>', note: '<role>', manager?: true }
// Order matters — longer/more specific patterns first so a full-name match
// wins over a first-name match. If empty, name detection is disabled.
const KNOWN_PEOPLE = (window.SEED && Array.isArray(window.SEED.knownPeople)) ? window.SEED.knownPeople : [];

const PEOPLE_REGEX = (() => {
  if (!KNOWN_PEOPLE.length) return null;
  const escape = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const sorted = [...KNOWN_PEOPLE].sort((a, b) => b.match.length - a.match.length);
  const alt = sorted.map(p => escape(p.match)).join('|');
  return new RegExp(`\\b(${alt})\\b`, 'g');
})();

// Wrap people-name occurrences in clickable spans that open the Stakeholder Lens.
// Falls back to the raw text when no matches are found.
function TextWithPeople({ text }) {
  if (!text) return null;
  if (!PEOPLE_REGEX) return text; // No people configured → render plain text
  // Reset regex state — RegExp /g objects are stateful across exec calls.
  PEOPLE_REGEX.lastIndex = 0;
  const parts = [];
  let lastIdx = 0;
  let m;
  let key = 0;
  while ((m = PEOPLE_REGEX.exec(text)) !== null) {
    if (m.index > lastIdx) parts.push(text.slice(lastIdx, m.index));
    const matchedText = m[0];
    const person = KNOWN_PEOPLE.find(p => p.match === matchedText)
                || KNOWN_PEOPLE.find(p => p.match.toLowerCase() === matchedText.toLowerCase());
    if (person) {
      parts.push(
        <span
          key={`p-${key++}`}
          className="text-person"
          onClick={(e) => {
            e.stopPropagation();
            window.dispatchEvent(new CustomEvent('dash:open-lens', { detail: { person } }));
          }}
          title={`Open lens for ${person.name}`}
          role="button"
          tabIndex={0}
        >{matchedText}</span>
      );
    } else {
      parts.push(matchedText);
    }
    lastIdx = m.index + matchedText.length;
  }
  if (lastIdx < text.length) parts.push(text.slice(lastIdx));
  return <>{parts}</>;
}

// --- Auto-prioritization: pure scoring helpers used by Top3 + suggestion line ---
// Score range typically 20-100. Higher = should be done sooner.
// Signals: deadline pressure (bucket), priority field (p), stakeholder seniority
// (text mentions of senior people), date recency (today/this week), blocked penalty.
const SENIOR_RANK = [
  // Order matters — first match wins so the most senior reason surfaces in the chip.
  { re: /\bceo\b/i,                               weight: 25, label: 'CEO' },
  { re: /\b(christopher\s+rogan|rogan)\b/i,       weight: 22, label: 'Rogan' },
  { re: /\bjose\b/i,                              weight: 20, label: 'Jose' },
  { re: /\bchristopher\b/i,                       weight: 15, label: 'Christopher' },
  { re: /\beze(quiel)?\b/i,                       weight: 14, label: 'Eze' },
  { re: /\bpaula\b/i,                             weight: 12, label: 'Paula' },
  { re: /\b(konstantinos|emily|mathew|sagat)\b/i, weight: 10, label: 'partner' },
];

function scoreTask(t, ctx = {}) {
  if (!t || t.done) return { score: 0, reasons: [] };
  let score = 0;
  const reasons = [];

  // Bucket = baseline urgency
  const bucket = ctx.bucket || 'dueSoon';
  if (bucket === 'overdue')        { score += 40; reasons.push('overdue'); }
  else if (bucket === 'top3')      { score += 30; reasons.push('top-3'); }
  else if (bucket === 'dueSoon')   { score += 25; reasons.push('due soon'); }
  else if (bucket === 'blocked')   { score += 15; reasons.push('blocked'); }

  // Priority field on the task itself
  if (t.p === 1)      { score += 20; reasons.push('P0'); }
  else if (t.p === 2) { score += 10; reasons.push('P1'); }

  // Stakeholder seniority — first match in the rank order
  const text = `${t.label || ''} ${t.meta || ''}`;
  for (const rule of SENIOR_RANK) {
    if (rule.re.test(text)) { score += rule.weight; reasons.push(rule.label); break; }
  }

  // Date recency hints in meta
  const metaLc = (t.meta || '').toLowerCase();
  if (/\btoday\b/.test(metaLc))            { score += 15; reasons.push('today'); }
  else if (/\bthis week\b/.test(metaLc))   { score += 8;  reasons.push('this wk'); }
  else if (/\btomorrow\b/.test(metaLc))    { score += 12; reasons.push('tomorrow'); }
  else if (/\bfri(day)?\b/.test(metaLc) || /\bthu(rsday)?\b/.test(metaLc) || /\bwed(nesday)?\b/.test(metaLc))
                                            { score += 5; }

  // OKR alignment via the tagger API (only counts confirmed tags, not suggestions)
  if (ctx.okrApi && typeof ctx.okrApi.getTag === 'function') {
    const tag = ctx.okrApi.getTag(t.label);
    if (tag === 'k1')      { score += 15; reasons.push('k1·AI'); }
    else if (tag)          { score += 10; reasons.push(tag); }
  }

  return { score, reasons };
}

// Score every open task across overdue + dueSoon + blocked + top3, return sorted desc.
function scoreAllOpen(SEED, okrApi) {
  const out = [];
  const push = (arr, bucket) => (arr || []).forEach(t => {
    if (t.done) return;
    const { score, reasons } = scoreTask(t, { bucket, okrApi });
    out.push({ ...t, _bucket: bucket, _score: score, _reasons: reasons });
  });
  push(SEED.top3,    'top3');
  push(SEED.overdue, 'overdue');
  push(SEED.dueSoon, 'dueSoon');
  push(SEED.blocked, 'blocked');
  out.sort((a, b) => b._score - a._score);
  return out;
}

// --- OkrTagger: shared chip + picker used on tasks, top3, decisions, shipped ---
// Three states:
//   confirmed (manual tag) → solid colored chip · click opens picker to change/remove
//   suggested (auto-match) → dashed faint chip with "?"  · click confirms it
//   untagged + no suggestion → tiny "+" appears on row hover · click opens picker
function OkrTagger({ label, meta, okrApi }) {
  const [open, setOpen] = useState(false);
  const rootRef = useRef(null);
  if (!okrApi) return null;
  const tag = okrApi.getTag(label);
  const suggested = !tag ? okrApi.getSuggestion(label, meta) : null;
  const effective = tag || suggested;

  useEffect(() => {
    if (!open) return;
    const handler = (e) => {
      if (rootRef.current && !rootRef.current.contains(e.target)) setOpen(false);
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [open]);

  const okrs = (window.SEED && window.SEED.okrs) || [];
  const okrName = (id) => (okrs.find(o => o.id === id) || {}).name || id;
  const M = okrApi.META || {};

  const onChipClick = (e) => {
    e.stopPropagation();
    if (suggested && !tag) {
      // confirm suggestion
      okrApi.setTag(label, suggested);
    } else {
      setOpen(o => !o);
    }
  };
  const onAddClick = (e) => { e.stopPropagation(); setOpen(o => !o); };

  return (
    <span ref={rootRef} className="okr-tagger" onClick={e => e.stopPropagation()}>
      {effective ? (
        <button
          className={'okr-chip' + (tag ? ' confirmed' : ' suggested')}
          onClick={onChipClick}
          title={tag
            ? `Tagged · ${okrName(tag)} · click to change`
            : `Suggested · ${okrName(suggested)} · click to confirm`}
          style={{
            background: M[effective] && M[effective].bg,
            color:      M[effective] && M[effective].ink,
            borderColor: M[effective] && M[effective].color,
          }}
        >
          {(M[effective] && M[effective].short) || effective}{!tag && '?'}
        </button>
      ) : (
        <button className="okr-add-btn" onClick={onAddClick} title="Tag to OKR">→</button>
      )}
      {open && (
        <div className="okr-picker">
          {['k1', 'k2', 'k3'].map(k => (
            <button
              key={k}
              className={'okr-picker-row' + (tag === k ? ' is-current' : '')}
              onClick={(e) => { e.stopPropagation(); okrApi.setTag(label, k); setOpen(false); }}
            >
              <span className="okr-picker-dot" style={{background: M[k] && M[k].color}}/>
              <span className="okr-picker-short">{M[k] && M[k].short}</span>
              <span className="okr-picker-name">{okrName(k)}</span>
            </button>
          ))}
          {tag && (
            <button
              className="okr-picker-row okr-picker-untag"
              onClick={(e) => { e.stopPropagation(); okrApi.setTag(label, null); setOpen(false); }}
            >
              <span className="okr-picker-dot okr-picker-dot-x">×</span>
              <span className="okr-picker-name">untag</span>
            </button>
          )}
        </div>
      )}
    </span>
  );
}

// --- Module shell ---
function Module({ title, count, sub, action, actionHref, onAction, right, icon, className, children, ...rest }) {
  return (
    <div className={'mod ' + (className || '')} {...rest}>
      <div className="mod-h">
        <div className="mod-h-l">
          {icon}
          <div>
            <div className="mod-title">
              {title}
              {count != null && <span className="count">{count}</span>}
            </div>
            {sub && <div className="mod-sub">{sub}</div>}
          </div>
        </div>
        <div className="mod-h-r">
          {right}
          {action && (actionHref
            ? <a className="link-all" href={actionHref} target="_blank" rel="noreferrer">{action}<Icon name="chevron-right" size={14}/></a>
            : <a className="link-all" href="#" onClick={e=>{e.preventDefault(); if (onAction) onAction(e);}}>{action}<Icon name="chevron-right" size={14}/></a>)}
        </div>
      </div>
      {children}
    </div>
  );
}

// --- Draggable task list ---
function useDraggable(initial) {
  const [items, setItems] = useState(initial);
  const dragId = useRef(null);
  const onDragStart = (id) => (e) => { dragId.current = id; e.dataTransfer.effectAllowed = 'move'; };
  const onDragOver  = (id) => (e) => { e.preventDefault(); e.currentTarget.classList.add('drag-over'); };
  const onDragLeave = (e) => { e.currentTarget.classList.remove('drag-over'); };
  const onDrop      = (id) => (e) => {
    e.preventDefault(); e.currentTarget.classList.remove('drag-over');
    const from = items.findIndex(i => i.id === dragId.current);
    const to   = items.findIndex(i => i.id === id);
    if (from < 0 || to < 0 || from === to) return;
    const next = items.slice();
    const [moved] = next.splice(from, 1);
    next.splice(to, 0, moved);
    setItems(next);
  };
  return { items, setItems, onDragStart, onDragOver, onDragLeave, onDrop };
}

// --- Top-3 Today (hero priority block) ---
function Top3({ data, onToggle, density, okrApi }) {
  const drag = useDraggable(data);
  useEffect(() => { drag.setItems(data); }, [data]);
  const now = new Date();
  const stamp = now.toLocaleString('en-US', { weekday: 'short', month: 'short', day: 'numeric' }).toUpperCase();

  // Score the live Top-3 items (label-keyed lookup so re-orders don't break it)
  const scored = useMemo(() => {
    const map = new Map();
    drag.items.forEach(it => map.set(it.id, scoreTask(it, { bucket: 'top3', okrApi })));
    return map;
  }, [drag.items, okrApi]);

  // Find the highest-scoring open task that is NOT in the Top-3 — if its score
  // beats the lowest-scoring Top-3 item, surface a "swap" suggestion.
  const suggestion = useMemo(() => {
    const all = scoreAllOpen(window.SEED || {}, okrApi);
    const top3Ids = new Set(drag.items.map(i => i.id));
    const candidate = all.find(t => !top3Ids.has(t.id));
    if (!candidate) return null;
    const lowestTop3 = Math.min(...drag.items.filter(i => !i.done).map(i => (scored.get(i.id) || {}).score || 0));
    if (candidate._score <= lowestTop3) return null;
    return { ...candidate, lowestTop3 };
  }, [drag.items, scored, okrApi]);

  return (
    <div className="top3 mod-focus-survivor">
      <div className="top3-h">
        <div className="top3-title">
          <span className="badge-star"><Icon name="lightning" size={14} style={{filter:'brightness(0)'}}/></span>
          What actually matters today
        </div>
        <div className="top3-stamp">{stamp} · {drag.items.filter(i=>!i.done).length} of 3 left</div>
      </div>
      <div className="top3-list">
        {drag.items.map((it, idx) => {
          const s = scored.get(it.id) || { score: 0, reasons: [] };
          return (
            <div key={it.id}
                 className={'top3-item' + (it.done ? ' done' : '')}
                 draggable
                 onDragStart={drag.onDragStart(it.id)}
                 onDragOver={drag.onDragOver(it.id)}
                 onDragLeave={drag.onDragLeave}
                 onDrop={drag.onDrop(it.id)}>
              <div className="top3-num">{String(idx + 1).padStart(2,'0')}</div>
              <div>
                <div className="top3-label"><TextWithPeople text={it.label}/></div>
                <div className="top3-meta"><TextWithPeople text={it.meta}/></div>
              </div>
              <div style={{display:'flex', alignItems:'center', gap:8}}>
                <OkrTagger label={it.label} meta={it.meta} okrApi={okrApi}/>
                <div className="top3-check" onClick={() => onToggle(it.id)} role="button" aria-label={it.done ? 'Mark incomplete' : 'Mark complete'}/>
              </div>
            </div>
          );
        })}
      </div>
      {suggestion && (
        <div className="top3-suggest" title={(suggestion._reasons || []).join(' · ')}>
          <span className="ts-tag">Algo suggests</span>
          <span className="ts-body">
            <strong><TextWithPeople text={suggestion.label}/></strong>
            <span className="ts-meta"><TextWithPeople text={suggestion.meta || ''}/></span>
          </span>
        </div>
      )}
    </div>
  );
}

// --- Simple task row used in tasks module (overdue / due-soon / blocked) ---
function TaskRow({ t, onToggle, onDismiss, okrApi, projectColor }) {
  return (
    <div className={'task-row' + (t.done ? ' done' : '')}>
      <div className="task-tick" data-done={t.done} onClick={() => onToggle(t.id)} role="button" aria-label="Toggle"/>
      <div className="task-body">
        <div className="task-title"><TextWithPeople text={t.label}/></div>
        <div className="task-meta">
          {projectColor && <span className="proj-dot" style={{background: projectColor}}/>}
          <TextWithPeople text={t.meta}/>
        </div>
      </div>
      <div style={{display:'flex', alignItems:'center', gap:8}}>
        {!t.done && <OkrTagger label={t.label} meta={t.meta} okrApi={okrApi}/>}
        {t.done
          ? <span className="done-flag" aria-label="Done">✓ done</span>
          : <span className="priority-flag" data-p={t.p}>P{t.p}</span>}
        {onDismiss && !t.done && (
          <button
            className="task-dismiss"
            onClick={(e) => { e.stopPropagation(); onDismiss(t.label); }}
            title="Dismiss for 14 days"
            aria-label="Dismiss task"
          >×</button>
        )}
        <img className="drag-grip" src="ds/assets/icons/drag-and-drop.svg" alt=""/>
      </div>
    </div>
  );
}

// --- Tasks & priorities module ---
function TasksMod({ state, onToggle }) {
  const projColor = (id) => {
    const map = {
      hiring: 'var(--pink-400)', ops: 'var(--grey-400)', partnerships: 'var(--blue-400)',
      infra: 'var(--teal-400)', contracts: 'var(--red-400)', brand: 'var(--yellow-400)', growth: 'var(--pink-400)',
    };
    return map[id] || 'var(--grey-300)';
  };
  const dismiss = state.dismissTask;
  const restore = state.restoreDismissed;
  const dismissedCount = state.dismissedCount || 0;
  return (
    <Module title="Tasks" sub="Only what moves today" action="Open list"
            icon={<span className="mod-icon-dot" style={{width:28, height:28, borderRadius:8, background:'var(--grey-100)', display:'grid', placeItems:'center'}}><Icon name="check-circle" size={16}/></span>}>
      {dismissedCount > 0 && (
        <div className="tasks-restore-strip">
          {dismissedCount} hidden
          <button onClick={restore}>restore</button>
        </div>
      )}
      {state.overdue.length > 0 && <>
        <div className="sub-section-head"><span style={{color:'var(--red-600)'}}>Overdue</span><span className="bar"/><span>{state.overdue.length}</span></div>
        {state.overdue.map(t => <TaskRow key={t.id + (t.done ? '-done' : '')} t={t} onToggle={onToggle} onDismiss={dismiss} okrApi={state.okrApi} projectColor={projColor(t.project)}/>)}
      </>}
      <div className="sub-section-head">Due soon<span className="bar"/><span>{state.dueSoon.length}</span></div>
      {state.dueSoon.map(t => <TaskRow key={t.id + (t.done ? '-done' : '')} t={t} onToggle={onToggle} onDismiss={dismiss} okrApi={state.okrApi} projectColor={projColor(t.project)}/>)}
      <div className="sub-section-head">Blocked on others<span className="bar"/><span>{state.blocked.length}</span></div>
      {state.blocked.map(t => <TaskRow key={t.id + (t.done ? '-done' : '')} t={t} onToggle={onToggle} onDismiss={dismiss} okrApi={state.okrApi} projectColor={projColor(t.project)}/>)}
      <div className="sub-section-head">Recently shipped<span className="bar"/><span>{state.shipped.length}</span></div>
      {state.shipped.map(s => (
        <div key={s.id} className="ship-row">
          <div className="tick"><Icon name="check" size={12}/></div>
          <div className="ship-body">
            <div className="ship-title">{s.title}</div>
          </div>
          <div className="ship-meta">{s.meta}</div>
          <OkrTagger label={s.title} meta={s.meta} okrApi={state.okrApi}/>
          {dismiss && (
            <button
              className="task-dismiss"
              onClick={(e) => { e.stopPropagation(); dismiss(s.title); }}
              title="Dismiss"
              aria-label="Dismiss"
            >×</button>
          )}
        </div>
      ))}
    </Module>
  );
}

// --- Calendar module ---
function CalendarMod({ data, next }) {
  const _nowDate = new Date();
  const NOW = `${String(_nowDate.getHours()).padStart(2,'0')}:${String(_nowDate.getMinutes()).padStart(2,'0')}`;
  const _dateLabel = _nowDate.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
  const _eventCount = (data && data.length) || 0;
  return (
    <Module title="Today" sub={`${_dateLabel} · ${_eventCount} event${_eventCount===1?'':'s'}`}
            icon={<span style={{width:28, height:28, borderRadius:8, background:'var(--grey-100)', display:'grid', placeItems:'center'}}><Icon name="calendar" size={16}/></span>}
            action="Week view" actionHref="https://calendar.google.com/calendar/u/0/r/week">
      <div className="countdown">
        <div className="cd-l">
          <div className="cd-title">{next.title}</div>
          <div className="cd-sub">with {next.with} · {next.room}</div>
        </div>
        <div className="cd-big">{next.startsIn}m</div>
      </div>
      <div style={{marginTop:4}}>
        {data.map((e, idx) => {
          const toMin = (t) => { const [h,m] = t.split(':').map(Number); return h*60+m; };
          const nowMin = toMin(NOW);
          const endMin = toMin(e.time) + (e.duration || 30);
          const pastEnd = endMin <= nowMin;
          const insertNow = idx > 0
            && toMin(data[idx-1].time) + (data[idx-1].duration||30) <= nowMin
            && toMin(e.time) >= nowMin;
          const displayType = pastEnd ? 'done' : e.type;
          return (
            <React.Fragment key={e.id}>
              {insertNow && (
                <div className="now-line">
                  <span className="now-line-label">Now · {NOW}</span>
                  <span className="now-line-bar"/>
                </div>
              )}
              <div className="cal-day">
                <div className="cal-time">{e.time}</div>
                <div className="cal-event" data-type={displayType}>
                  <div className="cal-title">{e.title}</div>
                  {e.who && (
                    <div className="cal-attendees">
                      <div className="cal-stack-avatars">
                        {e.who.slice(0,3).map((w,i) => (
                          <span key={i} className="pds-avatar size-24">
                            <img src="ds/assets/avatar-default.svg" alt={w}/>
                          </span>
                        ))}
                      </div>
                      <span>{e.who.slice(0,3).join(', ')}{e.who.length > 3 ? ` +${e.who.length - 3}` : ''}</span>
                    </div>
                  )}
                </div>
              </div>
            </React.Fragment>
          );
        })}
      </div>
    </Module>
  );
}

// --- Meeting load pill ---
function MeetingLoad({ data }) {
  const pct = Math.round((data.hoursThisWeek / data.hoursCap) * 100);
  return (
    <div style={{
      display:'flex', alignItems:'center', gap:12, padding:'12px 14px',
      border:'2px solid var(--border-default)', borderRadius:4, background:'var(--bg-surface)'
    }}>
      <div style={{
        width:42, height:42, borderRadius:10,
        background: data.hoursThisWeek > data.hoursCap ? 'var(--red-50)' : 'var(--grey-50)',
        display:'grid', placeItems:'center'
      }}>
        <Icon name="hourglass" size={20}/>
      </div>
      <div style={{flex:1, minWidth:0}}>
        <div style={{fontSize:12, fontWeight:600, color:'var(--fg-3)', letterSpacing:'0.04em', textTransform:'uppercase'}}>Meeting load</div>
        <div style={{fontFamily:'var(--font-display)', fontWeight:500, fontSize:20, lineHeight:1, marginTop:4}}>
          {data.hoursThisWeek}h <span style={{fontSize:13, color:'var(--fg-3)'}}>of {data.hoursCap}h</span>
        </div>
        <div style={{
          width:'100%', height:4, borderRadius:999, background:'var(--grey-100)',
          marginTop:6, position:'relative', overflow:'hidden'
        }}>
          <span style={{
            position:'absolute', inset:0, width:`${Math.min(100, pct)}%`,
            background: pct > 90 ? 'var(--red-500)' : 'var(--grey-900)', borderRadius:999
          }}/>
        </div>
      </div>
    </div>
  );
}

// --- Inbox module ---
function InboxMod({ data }) {
  const [items, setItems] = useState(data);
  useEffect(()=>{setItems(data)},[data]);
  return (
    <Module title="Inbox that matters" sub="Filtered · not raw counts" count={items.length}
            icon={<span style={{width:28, height:28, borderRadius:8, background:'var(--grey-100)', display:'grid', placeItems:'center'}}><Icon name="mail" size={16}/></span>}
            action="Open inbox" actionHref="https://mail.google.com/mail/u/0/#inbox"
            className="inbox-mod">
      {items.map(m => (
        <div key={m.id} className="inbox-row" onClick={()=>setItems(items.filter(x=>x.id!==m.id))}>
          <span className="pds-avatar size-32">
            <img src="ds/assets/avatar-default.svg" alt={m.from}/>
          </span>
          <div style={{minWidth:0}}>
            <div className="inbox-title">
              <span className="inbox-tag" data-t={m.tag}>{m.tag}</span>
              <span style={{color:'var(--fg-1)'}}>{m.from}</span>
              <span style={{color:'var(--fg-3)', fontWeight:400, fontSize:13}}>· {m.channel}</span>
            </div>
            <div className="inbox-preview">{m.title} — <span style={{color:'var(--fg-3)'}}>{m.preview}</span></div>
          </div>
          <div className="inbox-meta">{m.at}</div>
        </div>
      ))}
      {items.length === 0 && <div className="empty-ok"><span className="big">Inbox zero</span>Enjoy the quiet.</div>}
    </Module>
  );
}

// --- Free-form box (drag module header to move, drag edges to resize) ---
const BOX_MIN_W = 260, BOX_MIN_H = 140;
const DRAG_ZONE_SELECTOR = '.mod-h, .top3-h';
const IGNORE_SELECTOR = 'button, a, input, textarea, select, [role="button"], .box-rh, .task-tick, .top3-check, .inbox-row, .pin, .slack-row, .slack-tab, .slack-compose';

function DraggableBox({ id, box, onChange, onDragStart, onDragEnd, children }) {
  const ref = useRef(null);
  const [dragging, setDragging] = useState(false);

  const beginMove = (e) => {
    if (e.button !== 0) return;
    if (e.target.closest(IGNORE_SELECTOR)) return;
    if (!e.target.closest(DRAG_ZONE_SELECTOR)) return;
    e.preventDefault();
    setDragging(true);
    if (onDragStart) onDragStart(id);
    const sx = e.clientX, sy = e.clientY;
    const sL = box.left, sT = box.top;
    const onMove = (ev) => {
      onChange(id, { ...box, left: sL + (ev.clientX - sx), top: Math.max(0, sT + (ev.clientY - sy)) });
    };
    const onUp = () => {
      setDragging(false);
      if (onDragEnd) onDragEnd(id);
      document.removeEventListener('pointermove', onMove);
      document.removeEventListener('pointerup', onUp);
    };
    document.addEventListener('pointermove', onMove);
    document.addEventListener('pointerup', onUp);
  };

  const beginResize = (dir) => (e) => {
    if (e.button !== 0) return;
    e.preventDefault();
    e.stopPropagation();
    setDragging(true);
    if (onDragStart) onDragStart(id);
    const sx = e.clientX, sy = e.clientY;
    const sW = box.width, sH = box.height, sL = box.left, sT = box.top;
    const onMove = (ev) => {
      const dx = ev.clientX - sx, dy = ev.clientY - sy;
      let w = sW, h = sH, L = sL, T = sT;
      if (dir.includes('e')) w = Math.max(BOX_MIN_W, sW + dx);
      if (dir.includes('s')) h = Math.max(BOX_MIN_H, sH + dy);
      if (dir.includes('w')) { const nw = Math.max(BOX_MIN_W, sW - dx); L = sL + (sW - nw); w = nw; }
      if (dir.includes('n')) { const nh = Math.max(BOX_MIN_H, sH - dy); T = Math.max(0, sT + (sH - nh)); h = nh; }
      onChange(id, { ...box, left: L, top: T, width: w, height: h });
    };
    const onUp = () => {
      setDragging(false);
      if (onDragEnd) onDragEnd(id);
      document.removeEventListener('pointermove', onMove);
      document.removeEventListener('pointerup', onUp);
    };
    document.addEventListener('pointermove', onMove);
    document.addEventListener('pointerup', onUp);
  };

  return (
    <div ref={ref}
         className={'box' + (dragging ? ' box-dragging' : '')}
         style={{ left: box.left, top: box.top, width: box.width, height: box.height }}
         onPointerDown={beginMove}>
      <div className="box-inner">{children}</div>
      {['n','e','s','w','nw','ne','sw','se'].map(d => (
        <div key={d} className={`box-rh box-rh-${d}`} onPointerDown={beginResize(d)}/>
      ))}
    </div>
  );
}

Object.assign(window, { Icon, Module, Top3, TaskRow, TasksMod, CalendarMod, MeetingLoad, InboxMod, useDraggable, DraggableBox, BOX_MIN_W, BOX_MIN_H, OkrTagger, scoreTask, scoreAllOpen, TextWithPeople, KNOWN_PEOPLE });
